name: Jest Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install --no-progress --non-interactiv

    - name: Run test suite
      run: yarn test
